language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS divulgausados;" -uroot; fi

install: composer install

script: 
  - php artisan migrate
  - phpunit 
